<?php
/**
 * @file
 * Code for the Focus Populate feature.
 */

include_once 'focuspopulate.features.inc';


/**
 * Implementation of hook_perm().
 */
function focuspopulate_perm() {
  return array('Populate Focus Database');
}

//dpm($_SESSION['ip_geoloc']);

function focuspopulate_views_pre_view(&$view, &$display_id, &$args) {
  
  if (isset($_SESSION['ip_geoloc']['location']['locality']) && isset($_SESSION['ip_geoloc']['location']['administrative_area_level_1'])) {
    $city_state = $_SESSION['ip_geoloc']['location']['locality'] . ', ' . $_SESSION['ip_geoloc']['location']['administrative_area_level_1'];
  }
  else {
    $city_state = t('Newport, OR');
  }

  // set circle radius
  if (isset($_GET['circle']['value']) && is_numeric($_GET['circle']['value'])) {
    $radius = $_GET['circle']['value'];
  }
  else {
    $radius =  50;
  }

  if ($view->name == 'populatedatabase') {
    //dpm($view, 'view');

    $view->display['populate_bike']->handler->options['filters']['circle']['value']['value'] = $radius;
    $view->display['populate_bike']->handler->options['filters']['circle']['value']['location'] = $city_state;

    $view->display['populate_boat']->handler->options['filters']['circle']['value']['value'] = $radius;
    $view->display['populate_boat']->handler->options['filters']['circle']['value']['location'] = $city_state;

    $view->display['populate_climb']->handler->options['filters']['circle']['value']['value'] = $radius;
    $view->display['populate_climb']->handler->options['filters']['circle']['value']['location'] = $city_state;

    $view->display['populate_golf']->handler->options['filters']['circle']['value']['value'] = $radius;
    $view->display['populate_golf']->handler->options['filters']['circle']['value']['location'] = $city_state;

    $view->display['populate_skate']->handler->options['filters']['circle']['value']['value'] = $radius;
    $view->display['populate_skate']->handler->options['filters']['circle']['value']['location'] = $city_state;

    $view->display['populate_snow']->handler->options['filters']['circle']['value']['value'] = $radius;
    $view->display['populate_snow']->handler->options['filters']['circle']['value']['location'] = $city_state;

    $view->display['populate_surf']->handler->options['filters']['circle']['value']['value'] = $radius;
    $view->display['populate_surf']->handler->options['filters']['circle']['value']['location'] = $city_state;
    
  }

}

function focuspopulate_form_alter(&$form, &$form_state, $form_id) {

  //dpm($form);
  switch ($form_id) {
    
    case 'views_exposed_form':
      if ($form['#id'] == 'views-exposed-form-populatedatabase-populate-bike'   || 
        $form['#id'] == 'views-exposed-form-populatedatabase-populate-boat'     || 
        $form['#id'] == 'views-exposed-form-populatedatabase-populate-climb'    || 
        $form['#id'] == 'views-exposed-form-populatedatabase-populate-golf'     || 
        $form['#id'] == 'views-exposed-form-populatedatabase-populate-skate'    || 
        $form['#id'] == 'views-exposed-form-populatedatabase-populate-snow'     ||
        $form['#id'] == 'views-exposed-form-populatedatabase-populate-surf') {    

        $form['submit'] = array(
          '#type' => 'image_button',
          '#src' => drupal_get_path('module', 'gozulla_directory') .'/images/go_btn.png',
        );
 
        $form['circle']['location']['#field_prefix'] = '+'; 

        $form['circle']['value']['#field_prefix'] =  t('<span id="findme"><a href="#" id="findme-link">FIND ME</a></span> or search '); 
        $form['circle']['value']['#field_suffix'] = t('mi '); 

      }
      
    break;
  }
}

/**
 * Constructs a sports directory page.
 */
function focuspopulate_disc() {
  return array('#markup' => '
    <ul>
      <li>
        <div id="disc-directory">' . t('disc golf directory coming soon') . '</div>
      </li>
    </ul>
    '
  );
}


/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function focuspopulate_block_info() {

  $blocks['populate_bike'] = array(
    // info: The name of the block.
    'info' => t('focuspopulate: bike shops (google places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'bike',
  );
  
  $blocks['populate_boat'] = array(
    // info: The name of the block.
    'info' => t('focuspopulate: boat shops (google places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'boat',
  );

  $blocks['populate_climb'] = array(
    // info: The name of the block.
    'info' => t('focuspopulate: climb shops (google places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'climb',
  );  
  
  $blocks['populate_golf'] = array(
    // info: The name of the block.
    'info' => t('focuspopulate: golf shops (google places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'golf',
  );
  
  $blocks['populate_skate'] = array(
    // info: The name of the block.
    'info' => t('focuspopulate: skate shops (google places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'skate',
  );
  
  $blocks['populate_snow'] = array(
    // info: The name of the block.
    'info' => t('focuspopulate: snow shops (google places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'snow',
  );
  
  $blocks['populate_surf'] = array(
    // info: The name of the block.
    'info' => t('focuspopulate: surf shops (google places)'),
    'status' => TRUE,
    'region' => 'content', 
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'surf',
  );

  return $blocks;

}


/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function focuspopulate_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  $block = '';
  switch ($delta) {

    case 'populate_bike':

      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break;
      
    case 'populate_boat':
      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break;  
      
    case 'populate_climb':
      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break;

    case 'populate_golf':
      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break; 

    case 'populate_skate':
      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break;
      
    case 'populate_snow':
      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break;

    case 'populate_surf':
      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break;

    case 'lodging':
      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break;  

    default:
      $block['subject'] = t('');
      $block['content'] = focuspopulate_contents($delta);
      break;
          
  }

  return $block;

}

/**
 * A module-defined block content function.
 */
function focuspopulate_contents($which_block) {
  //$shops = array();
  $sport = 'all';
  switch ($which_block) {
      
    case 'populate_bike':

      $sport = 'bike';
      include_once('focuspopulate_shops.inc'); // common include
      return array('#markup' => $shops);
      break;
        
    case 'populate_boat':
      $sport = 'boat';
      include_once('focuspopulate_shops.inc'); // common include
      return array('#markup' => $shops);
      break; 
      
    case 'populate_climb':
      $sport = 'climb';
      include_once('focuspopulate_shops.inc'); // common include
      return array('#markup' => $shops);
      break;
      
    case 'populate_golf':
      $sport = 'golf';
      include_once('focuspopulate_shops.inc'); // common include
      return array('#markup' => $shops);
      break; 

    case 'populate_skate':
      $sport = 'skate';
      include_once('focuspopulate_shops.inc'); // common include
      return array('#markup' => $shops);
      break; 
      
    case 'populate_snow':
      $sport = 'snow';
      include_once('focuspopulate_shops.inc'); // common include
      return array('#markup' => $shops);
      break; 

    case 'populate_surf':
      $sport = 'surf';
      include_once('focuspopulate_shops.inc'); // common include
      return array('#markup' => $shops);
      break;


    // default:
    //   $sport = 'default';
    //   include_once('focuspopulate_shops.inc'); // common include
    //   return array('#markup' => $shops);
    //   break; 

  }

}